##########################################################################################
##### User ######
##########################################################################################

# Get all users LOCALHOST
GET http://localhost:8082/users

# Get a specific user by ID LOCALHOST
###
GET http://localhost:8082/users/6529f3904db2eab77d05af0e
###
GET http://localhost:8082/users/6529f3904db2eab77d05af0f
###
GET http://localhost:8082/users/6529f3904db2eab77d05af10
###
GET http://localhost:8082/users/6529f3904db2eab77d05af11
###
GET http://localhost:8082/users/6529f3904db2eab77d05af12


### Test POST
GET http://localhost:8082/users/6529f3904db2eab77d05af12

### Create User

POST http://localhost:8082/users HTTP/1.1
content-type: application/json

 {
    "username": "Buddy",
    "species": "Dog",
    "breed": "German Shepherd",
    "color": "Black and Tan",
    "gender": "Male",
    "age": 6,
    "owner": {
        "ownerName": "Sarah Johnson",
        "ownerEmail": "sarah.johnson@gmail.com",
        "ownerPhoneNumber": "555-555-5555",
        "ownerAddress": "204 Maple Avenue"
    },
    "vaccines": [
        {
            "vaccineType": "Parvovirus",
            "date": "2022-06-18",
            "secondDose": true
        }
    ],
    "vet": {
        "vetName": "Dr. Martinez",
        "vetSpecialization": ["Orthopedics"],
        "vetEmail": "drmartinez@gmail.com",
        "vetPhoneNumber": "555-555-5555"
    }
}

### Update User
PUT http://localhost:8082/users/6529f3904db2eab77d05af12 HTTP/1.1
content-type: application/json

{
    "username": "Luna",
    "species": "Dog",
    "breed": "German Shepherd",
    "color": "Black",
    "gender": "Female",
    "age": 4,
    "owner": {
        "ownerName": "Sarah Johnson",
        "ownerEmail": "sarah.johnson@gmail.com",
        "ownerPhoneNumber": "555-555-5555",
        "ownerAddress": "204 Maple Avenue"
    },
    "vaccines": [
        {
            "vaccineType": "Parvovirus",
            "date": "2022-06-18",
            "secondDose": true
        }
    ],
    "vet": {
        "vetName": "Dr. Martinez",
        "vetSpecialization": ["Orthopedics"],
        "vetEmail": "drmartinez@gmail.com",
        "vetPhoneNumber": "555-555-5555"
    }
}

### Delete User

DELETE http://localhost:8082/users/6529f3904db2eab77d05af12 HTTP/1.1


#################################################

# Get all users RENDER
GET https://lemos-cse341-personal.onrender.com/users

# Get a specific user by ID RENDER
###
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af0e
###
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af0f
###
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af10
###
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af11
###
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af12

### Test POST
GET https://lemos-cse341-personal.onrender.com/users/6529f3904db2eab77d05af11

### Create User

POST https://lemos-cse341-personal.onrender.com/users HTTP/1.1
content-type: application/json

{
    "username": "Buddy",
    "species": "Dog",
    "breed": "German Shepherd",
    "color": "Black and Tan",
    "gender": "Male",
    "age": 6,
    "owner": {
        "ownerName": "Sarah Johnson",
        "ownerEmail": "sarah.johnson@gmail.com",
        "ownerPhoneNumber": "555-555-5555",
        "ownerAddress": "204 Maple Avenue"
    },
    "vaccines": [
        {
            "vaccineType": "Parvovirus",
            "date": "2022-06-18",
            "secondDose": true
        }
    ],
    "vet": {
        "vetName": "Dr. Martinez",
        "vetSpecialization": ["Orthopedics"],
        "vetEmail": "drmartinez@gmail.com",
        "vetPhoneNumber": "555-555-5555"
    }
}

### Update User
PUT http://lemos-cse341-personal.onrender.com/users/652aae1bd7ca3657eeaa00ea HTTP/1.1
content-type: application/json

{
    "username": "Luna",
    "species": "Dog",
    "breed": "German Shepherd",
    "color": "Black",
    "gender": "Female",
    "age": 4,
    "owner": {
        "ownerName": "Sarah Johnson",
        "ownerEmail": "sarah.johnson@gmail.com",
        "ownerPhoneNumber": "555-555-5555",
        "ownerAddress": "204 Maple Avenue"
    },
    "vaccines": [
        {
            "vaccineType": "Parvovirus",
            "date": "2022-06-18",
            "secondDose": true
        }
    ],
    "vet": {
        "vetName": "Dr. Martinez",
        "vetSpecialization": ["Orthopedics"],
        "vetEmail": "drmartinez@gmail.com",
        "vetPhoneNumber": "555-555-5555"
    }
}

### Delete User

DELETE https://lemos-cse341-personal.onrender.com/users/652aae1bd7ca3657eeaa00ea HTTP/1.1

##########################################################################################
##### Review ######
##########################################################################################

# Get all reviews LOCALHOST
GET http://localhost:8082/reviews

# Get a specific review by ID LOCALHOST
###
GET http://localhost:8082/reviews/65276330bf159f70ea2e0f47
###
GET http://localhost:8082/reviews/652a16a02f4a246207124a6a
###
GET http://localhost:8082/reviews/652a17152f4a246207124a6b
###
GET http://localhost:8082/reviews/652a178c2f4a246207124a6c
###
GET http://localhost:8082/reviews/652a2856b3987af6bf6b85af
###
GET http://localhost:8082/reviews/652ab21ff45856f769d377a3
###
GET http://localhost:8082/reviews/652ab300f45856f769d377a4


### Test POST
GET http://localhost:8082/reviews/652a2856b3987af6bf6b85af

### Create Review

POST http://localhost:8082/reviews HTTP/1.1
content-type: application/json

  {
    "rating": 4,
    "comment": "My cat was feeling okay, so I am happy!"         
  }

### Update Review
PUT http://localhost:8082/reviews/653402b1cf94dacbd279ab3c HTTP/1.1
content-type: application/json

 {
    "rating": 5,
    "comment": "My cat was feeling awesome, so I am happy!"         
  }

### Delete Review

DELETE http://localhost:8082/reviews/653402b1cf94dacbd279ab3c HTTP/1.1


#################################################

# Get all Reviews RENDER
GET https://lemos-cse341-personal.onrender.com/reviews

# Get a specific review by ID RENDER
###
GET https://lemos-cse341-personal.onrender.com/reviews/65276330bf159f70ea2e0f47
###
GET https://lemos-cse341-personal.onrender.com/reviews/652a16a02f4a246207124a6a
###
GET https://lemos-cse341-personal.onrender.com/reviews/652a17152f4a246207124a6b
###
GET https://lemos-cse341-personal.onrender.com/reviews/652a178c2f4a246207124a6c
###
GET https://lemos-cse341-personal.onrender.com/reviews/6652a2856b3987af6bf6b85af
###
GET https://lemos-cse341-personal.onrender.com/reviews/652ab21ff45856f769d377a3
###
GET https://lemos-cse341-personal.onrender.com/reviews/652ab300f45856f769d377a4

### Test POST
GET https://lemos-cse341-personal.onrender.com/reviews/652a2856b3987af6bf6b85af

### Create Review

POST https://lemos-cse341-personal.onrender.com/reviews HTTP/1.1
content-type: application/json

{
    "rating": 4,
    "comment": "My cat was feeling okay, so I am happy!"         
}

### Update Review
PUT http://lemos-cse341-personal.onrender.com/reviews/652a2856b3987af6bf6b85af HTTP/1.1
content-type: application/json

{
    "rating": 5,
    "comment": "My cat was feeling awesome, so I am happy!"         
}

### Delete Review

DELETE https://lemos-cse341-personal.onrender.com/reviews/652a2856b3987af6bf6b85af HTTP/1.1




